stdout of test 'tst304` in directory 'monetdb5/mal` itself:


# 08:01:16 >  
# 08:01:16 >  Mtimeout -timeout 60 Mserver "--config=/ufs/mk/monet5/Linux/etc/MonetDB5.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/log" --set mapi_port=42158 --set sql_port=55708 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst304.mal </dev/null
# 08:01:16 >  

# MonetDB Server v4.99.19
# Copyright (c) 1993-2006 CWI, all rights reserved
# Compiled for x86_64-pc-linux-gnu/64bit with 64bit OIDs dynamically linked
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
## Exceptions can be explicitly raised in a function
## which requires the exception identifier to be defined.
#
#function myException();
#raise	IllegalAccess:="new exception";
#	print("should have left function ");
#end myException;
function user.myException():void;
    raise PermissionDeniedException := "new exception\n";
    io.print("should have left function ");
end myException;
#
#	myException();
#	print("should not come here");
##exception block;
#catch	IllegalAccess;
#	printf("caught IllegalAccess\n");
#exit	IllegalAccess;
#	print("done");
#
function user.main():void;
# Exceptions can be explicitly raised in a function 
# which requires the exception identifier to be defined. 
    user.myException();
    io.print("should not come here");
#exception block; 
catch MALException:str ;
    io.printf("caught IllegalAccess\n");
exit MALException:str ;
    io.print("done");
end main;
caught IllegalAccess
[ "done" ]

#

# 08:01:16 >  
# 08:01:16 >  Done.
# 08:01:16 >  

