stderr of test 'remote01` in directory 'monetdb5/modules/mal` itself:


# 09:35:17 >  
# 09:35:17 >  Mtimeout -timeout 60  mserver5 "--config=/ufs/fabian/scratch/monetdb/current/program-x86_64/etc/monetdb5.conf" --debug=10 --set "monet_mod_path=/ufs/fabian/scratch/monetdb/current/program-x86_64/lib64/MonetDB5:/ufs/fabian/scratch/monetdb/current/program-x86_64/lib64/MonetDB5/lib:/ufs/fabian/scratch/monetdb/current/program-x86_64/lib64/MonetDB5/bin" --set "gdk_dbfarm=/net/pegasus.ins.cwi.nl/export/scratch0/fabian/vtmp/mtest-current-pegasus.ins.cwi.nl/five/dbfarm" --set "sql_logdir=/net/pegasus.ins.cwi.nl/export/scratch0/fabian/vtmp/mtest-current-pegasus.ins.cwi.nl/five/sqllog" --set "xquery_logdir=/net/pegasus.ins.cwi.nl/export/scratch0/fabian/vtmp/mtest-current-pegasus.ins.cwi.nl/five/xquerylog" --set mapi_open=true --set mapi_port=37413 --set xrpc_port=46951 --set monet_prompt= --trace --dbname=mTests_src_modules_mal  remote01.mal
# 09:35:17 >  

#warning: please don't forget to set your vault key!
#(see /ufs/fabian/scratch/monetdb/current/program-x86_64/etc/monetdb5.conf)


# 09:35:17 >  
# 09:35:17 >  Done.
# 09:35:17 >  

